version: '3.7'

services:
  node:
    build: ./node
    image: heitordkr/nodeapp
    container_name: nodeapp
    command: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - mynet

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - node
    networks:
      - mynet

networks:
  mynet: